### ISSUE TITLE
Couldnt load gmhtml

### ISSUE THREAD

**Issue by ar1a** [Leystryku/die_awesomium#2]
on start engine error looking for gmhtml001 or whatever

**Comment by ar1a** [comment]
http://www.snorflake.com/u/1UMj.png

**Comment by TheTechPony** [comment]
I'm getting this as well.
https://gyazo.com/1dcabec0a2094c0c5953509105544489.png

**Comment by Leystryku** [comment]
Well I was working on a update, formatted my PC and noticed that I forgot to back it up. 
I tried restoring it, but since I'm using a SSD with TRIM - I couldn't restore it. :c:
I cba to update it, so it's dead now.

**Comment by TheTechPony** [comment]
So what does this mean? The project is dead?

**Comment by Leystryku** [comment]
yes pretty much

**Comment by TheTechPony** [comment]
well rip. It was a good run.
